app/__init__.py
from flask import Flask
import os
import ConfigParser
from logging.handlers import RotatingFileHandler
from flask.ext.pymongo import PyMongo
from flask.ext.cors import CORS
from app.utils.mongo_utils import MongoUtils

# Create MongoDB database object.
mongo = PyMongo()

#Initialize mongo access point
mongo_utils = MongoUtils(mongo)

def create_app():
    # Here we  create flask instance
    app = Flask(__name__)

    # Allow cross-domain access to API.
    #cors = CORS(app, resources={r"/api/*": {"origins": "*"}})

    # Load application configurations
    load_config(app)

    # Configure logging.
    configure_logging(app)

    # Init modules
    init_modules(app)

    # Initialize the app to work with MongoDB
    mongo.init_app(app, config_prefix='MONGO')

    return app


def load_config(app):
    ''' Reads the config file and loads configuration properties into the Flask app.
    :param app: The Flask app object.
    '''
    # Get the path to the application directory, that's where the config file resides.
    par_dir = os.path.join(__file__, os.pardir)
    par_dir_abs_path = os.path.abspath(par_dir)
    app_dir = os.path.dirname(par_dir_abs_path)

    # Read config file
    config = ConfigParser.RawConfigParser()
    config_filepath = app_dir + '/config.cfg'
    config.read(config_filepath)

    app.config['SERVER_PORT'] = config.get('Application', 'SERVER_PORT')
    app.config['MONGO_DBNAME'] = config.get('Mongo', 'DB_NAME')

    # Logging path might be relative or starts from the root.
    # If it's relative then be sure to prepend the path with the application's root directory path.
    log_path = config.get('Logging', 'PATH')
    if log_path.startswith('/'):
        app.config['LOG_PATH'] = log_path
    else:
        app.config['LOG_PATH'] = app_dir + '/' + log_path

    app.config['LOG_LEVEL'] = config.get('Logging', 'LEVEL').upper()


def configure_logging(app):
    ''' Configure the app's logging.
     param app: The Flask app object
    '''

    log_path = app.config['LOG_PATH']
    log_level = app.config['LOG_LEVEL']

    # If path directory doesn't exist, create it.
    log_dir = os.path.dirname(log_path)
    if not os.path.exists(log_dir):
        os.makedirs(log_dir)

    # Create and register the log file handler.
    log_handler = RotatingFileHandler(log_path, maxBytes=250000, backupCount=5)
    log_handler.setLevel(log_level)
    app.logger.addHandler(log_handler)

    # First log informs where we are logging to.
    # Bit silly but serves  as a confirmation that logging works.
    app.logger.info('Logging to: %s', log_path)


def init_modules(app):

    # Import blueprint modules
    from app.mod_main.views import mod_main

    app.register_blueprint(mod_main)

app/mod_main/views.py
from flask import Blueprint, Response, render_template, request, redirect, url_for
from app import mongo
from bson import ObjectId
from bson.json_util import dumps

mod_main = Blueprint('main', __name__)


@mod_main.route('/')
def index():
	return render_template("index.html")

@mod_main.route('/form',methods=['GET','POST'])
def form():
	if request.method == 'GET':
		emri="Roza"
		return render_template("form.html", emri=emri)
	elif request.method == 'POST':
		db = mongo.db.arkep
		form_data = request.form.to_dict()
		data = {

		  "nderrmarja":{

			"emri": form_data['emri_ndermarrjes'],

			"numri_regjistrimi":form_data['nr_regjistrimit'],

			"adresa":form_data['adresa'],

			"personi_kontaktues":form_data['personi_kontaktues'],

			"telefoni":form_data['telefoni'],

			"email":form_data['email']

			}

		}
		print data
		
		db.insert(data)
		return render_template("form.html", mesazhi="Faleminderit,forma u insertua!")
	else:
		return"Go home, you're drunk"

@mod_main.route('/list', methods=['GET'])
def list():
	db= mongo.db.arkep
	rekordet=db.find()
	return render_template('list.html', rekordet=rekordet)

 #@mod_main.route('/remove/<string:remove_id>', methods=['POST'])
#def remove(remove_id):
   # db= mongo.db.arkep
   # remove= db.remove({"_id" : ObjectId(remove_id)})
	#return Response(200)
@mod_main.route('/remove/<string:remove_id>', methods=['POST'])
def remove(remove_id):
	db = mongo.db.arkep
	remove = db.remove({"_id" : ObjectId(remove_id)})
	if remove['n'] == 1:
		return Response(response=dumps({"removed": True}),
		status=200,
		mimetype='application/json')
	else:
		return Response(response=dumps({"removed": False}),
		status=500,
		mimetype='application/json')

@mod_main.route('/raporti/<string:report_id>')
def raporti(report_id):
	db = mongo.db.arkep
	report=db.find_one({"_id": ObjectId(report_id)})

	return render_template('raporti.html', report=report)

@mod_main.route('/home', methods=['GET'])
def home():
	db = mongo.db.arkep
	return render_template('home.html', home=home)

app/templates/home.html
{% extends 'index.html'%}
{% block form %}
 <!DOCTYPE html>
 <html>
 <head>
  <nav>
  	
    <div class="nav-wrapper">
    <a href="home" class="brand-logo">ARKEP</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="form">Forma</a></li>
        <li><a href="list">Lista</a></li>
      </ul>

    </div>
    <div class="brand-logo" style="width: 490px;">
    <a title="ART logo" href="?cid=1,1">
    	<img src="../img/logo.png" alt="ART"></img></a>
    </div>
		
  </nav>
  

  <style>
nav {background-color: lightsteelblue; }

</style>

 </head>
 <body>
  	 
 </body>
 </html>
 {% endblock form %}

app/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Techstitution</title>
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='style.css')}}">
<script src="//code.jquery.com/jquery-3.1.1.min.js"></script>
	<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<!-- materialize css -->
<!-- Compiled and minified CSS -->
 <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">  <!-- Compiled and minified JavaScript -->
 <script src="//cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
</head>
	<body>
	{% block form%}
	{% endblock form %}

	</body>
</html>

app/templates/list.html
{% extends 'index.html'%}
{% block form %}
<script type="text/javascript">
	$(document).ready(function(){
		$('.remove').click(function(event){
			event.preventDefault();
			var url = this.href;
			var id = this.id;
			$.post(url, function(data){
				if(data.removed == true){
					$('#'+id).parent().parent().remove();
				}
				
			}).fail(function(){
				alert("Something wrong happened");
			});;
		});
	});
</script>
<table class="table">
	<tr>
		<th>Emri</th>
		<th>Email</th>
		<th>Actions</th>
	</tr>
{% for rekordi in rekordet %}
	<tr>
	<td>{{ rekordi['nderrmarja']['emri'] }}</td>
	<td>{{ rekordi['nderrmarja']['email'] }}</td>
	<td> 
	<a class="remove" id="{{ rekordi._id }}" href="{{ url_for('main.remove' , remove_id=rekordi._id)}}" > Delete</a> |
	<a href="{{ url_for('main.raporti' , report_id=rekordi._id)}}">View</a> 
	</td>
</tr>
	{% endfor %}
</table>

{% endblock %}

app/templates/raporti.html
{% extends 'index.html'%}
{% block form %}
<div class="container">
<div class="row">
<div class="col-md-6 col-md-offset-3">
<br /><br /><br />
<dl class ="dl-horizontal">
	<dt>Emri:</dt>
	<dd>{{report['nderrmarja']['emri'] }}</dd>


	<dt>Personi Kontaktues: </dt>
	<dd>{{report['nderrmarja']['personi_kontaktues'] }}</dd>


	<dt>Numri i Regjistrimit: </dt>
	<dd>{{report['nderrmarja']['numri_regjistrimi'] }}</dd>


	<dt>Adresa: </dt>
	<dd>{{report['nderrmarja']['adresa'] }}</dd>


	<dt>Telefoni:</dt>
	<dd>{{report['nderrmarja']['telefoni'] }}</dd>


	<dt>Email:</dt>
	<dd>{{report['nderrmarja']['email']}}</dd>
</dl>

		</div>
	</div>
</div>
{%endblock form%}